# Generated by Django 5.2 on 2025-05-21 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toys', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='toy',
            options={'ordering': ['-name']},
        ),
        migrations.RenameField(
            model_name='toy',
            old_name='created',
            new_name='release_date',
        ),
        migrations.RenameField(
            model_name='toy',
            old_name='category',
            new_name='toy_category',
        ),
        migrations.RemoveField(
            model_name='toy',
            name='available',
        ),
        migrations.RemoveField(
            model_name='toy',
            name='price',
        ),
        migrations.RemoveField(
            model_name='toy',
            name='updated',
        ),
        migrations.AddField(
            model_name='toy',
            name='was_included_in_home',
            field=models.BooleanField(default=False),
        ),
    ]
